## Pre-processing to split the dataset into train and test dataset

In [50]:
# Create data/input directory if it is not exists in current directory
!mkdir -p data/input

In [51]:
# Create data/preprocess director if it is not exists in current directory
!mkdir -p data/preprocess

In [52]:
# Download input dataset into local directory
!wget https://storage.googleapis.com/advanced-solutions-lab/fraud/creditcard.csv -O ./data/input/creditcard.csv

--2018-11-15 12:06:36--  https://storage.googleapis.com/advanced-solutions-lab/fraud/creditcard.csv
Resolving storage.googleapis.com (storage.googleapis.com)... 173.194.76.128, 2a00:1450:400c:c00::80
Connecting to storage.googleapis.com (storage.googleapis.com)|173.194.76.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 150828752 (144M) [text/csv]
Saving to: ‘./data/input/creditcard.csv’

./data/input/credit 100%[===================>] 143.84M   110MB/s    in 1.3s

2018-11-15 12:06:38 (110 MB/s) - ‘./data/input/creditcard.csv’ saved [150828752/150828752]

In [1]:
# import library functions
import pandas as pd

In [2]:
# Pandas display column upto 50
pd.set_option("display.max_columns",50)

In [3]:
df = pd.read_csv('./data/input/creditcard.csv')

In [4]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,-0.551600,-0.617801,-0.991390,-0.311169,1.468177,-0.470401,0.207971,0.025791,0.403993,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,1.612727,1.065235,0.489095,-0.143772,0.635558,0.463917,-0.114805,-0.183361,-0.145783,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,0.624501,0.066084,0.717293,-0.165946,2.345865,-2.890083,1.109969,-0.121359,-2.261857,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,-0.226487,0.178228,0.507757,-0.287924,-0.631418,-1.059647,-0.684093,1.965775,-1.232622,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,-0.822843,0.538196,1.345852,-1.119670,0.175121,-0.451449,-0.237033,-0.038195,0.803487,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [5]:
df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,1.165980e-15,3.416908e-16,-1.373150e-15,2.086869e-15,9.604066e-16,1.490107e-15,-5.556467e-16,1.177556e-16,-2.406455e-15,2.239751e-15,1.673327e-15,-1.254995e-15,8.176030e-16,1.206296e-15,4.913003e-15,1.437666e-15,-3.800113e-16,9.572133e-16,1.039817e-15,6.406703e-16,1.656562e-16,-3.444850e-16,2.578648e-16,4.471968e-15,5.340915e-16,1.687098e-15,-3.666453e-16,-1.220404e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,1.088850e+00,1.020713e+00,9.992014e-01,9.952742e-01,9.585956e-01,9.153160e-01,8.762529e-01,8.493371e-01,8.381762e-01,8.140405e-01,7.709250e-01,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,-2.458826e+01,-4.797473e+00,-1.868371e+01,-5.791881e+00,-1.921433e+01,-4.498945e+00,-1.412985e+01,-2.516280e+01,-9.498746e+00,-7.213527e+00,-5.449772e+01,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,-5.354257e-01,-7.624942e-01,-4.055715e-01,-6.485393e-01,-4.255740e-01,-5.828843e-01,-4.680368e-01,-4.837483e-01,-4.988498e-01,-4.562989e-01,-2.117214e-01,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,-9.291738e-02,-3.275735e-02,1.400326e-01,-1.356806e-02,5.060132e-02,4.807155e-02,6.641332e-02,-6.567575e-02,-3.636312e-03,3.734823e-03,-6.248109e-02,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,4.539234e-01,7.395934e-01,6.182380e-01,6.625050e-01,4.931498e-01,6.488208e-01,5.232963e-01,3.996750e-01,5.008067e-01,4.589494e-01,1.330408e-01,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,2.374514e+01,1.201891e+01,7.848392e+00,7.126883e+00,1.052677e+01,8.877742e+00,1.731511e+01,9.253526e+00,5.041069e+00,5.591971e+00,3.942090e+01,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [6]:
#Drop all of the features that have very similar distributions between the two types of transactions.
df = df.drop(['V28','V27','V26','V25','V24','V23','V22','V20','V15','V13','V8'], axis =1)

In [7]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V9,V10,V11,V12,V14,V16,V17,V18,V19,V21,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.363787,0.090794,-0.551600,-0.617801,-0.311169,-0.470401,0.207971,0.025791,0.403993,-0.018307,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,-0.255425,-0.166974,1.612727,1.065235,-0.143772,0.463917,-0.114805,-0.183361,-0.145783,-0.225775,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,-1.514654,0.207643,0.624501,0.066084,-0.165946,-2.890083,1.109969,-0.121359,-2.261857,0.247998,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,-1.387024,-0.054952,-0.226487,0.178228,-0.287924,-1.059647,-0.684093,1.965775,-1.232622,-0.108300,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,0.817739,0.753074,-0.822843,0.538196,-1.119670,-0.451449,-0.237033,-0.038195,0.803487,-0.009431,69.99,0

In [8]:
#Create dataframes of only Fraud and Normal transactions.
df_fraud = df[df.Class == 1]
df_normal = df[df.Class == 0]

In [9]:
df_fraud.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V9,V10,V11,V12,V14,V16,V17,V18,V19,V21,Amount,Class
541,406.0,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,-2.770089,-2.772272,3.202033,-2.899907,-4.289254,-1.140747,-2.830056,-0.016822,0.416956,0.517232,0.00,1
623,472.0,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.270953,-0.838587,-0.414575,-0.503141,-1.692029,0.666780,0.599717,1.725321,0.283345,0.661696,529.00,1
4920,4462.0,-2.303350,1.759247,-0.359745,2.330243,-0.821628,-0.075788,0.562320,-0.238253,-1.525412,2.032912,-6.560124,-1.470102,-2.282194,-4.781831,-2.615665,-1.334441,-0.294166,239.93,1
6108,6986.0,-4.397974,1.358367,-2.592844,2.679787,-1.128131,-1.706536,-3.496197,-0.247768,-4.801637,4.895844,-10.912819,-6.771097,-7.358083,-12.598419,-5.131549,0.308334,0.573574,59.00,1
6329,7519.0,1.234235,3.019740,-4.304597,4.732795,3.624201,-1.357746,1.713445,-1.282858,-2.447469,2.101344,-4.609628,-6.079337,2.581851,6.739384,3.042493,-2.721853,-0.379068,1.00,1

In [10]:
df_normal.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V9,V10,V11,V12,V14,V16,V17,V18,V19,V21,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.363787,0.090794,-0.551600,-0.617801,-0.311169,-0.470401,0.207971,0.025791,0.403993,-0.018307,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,-0.255425,-0.166974,1.612727,1.065235,-0.143772,0.463917,-0.114805,-0.183361,-0.145783,-0.225775,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,-1.514654,0.207643,0.624501,0.066084,-0.165946,-2.890083,1.109969,-0.121359,-2.261857,0.247998,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,-1.387024,-0.054952,-0.226487,0.178228,-0.287924,-1.059647,-0.684093,1.965775,-1.232622,-0.108300,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,0.817739,0.753074,-0.822843,0.538196,-1.119670,-0.451449,-0.237033,-0.038195,0.803487,-0.009431,69.99,0

In [11]:
# Set df_train equal to 80% of the fraudulent transactions.
df_train = df_fraud.sample(frac=0.8)

# Add 80% of the normal transactions to df_train.
df_train = pd.concat([df_train, df_normal.sample(frac = 0.8)], axis = 0)

# df_test contains all the transaction not in df_train.
df_test = df.loc[~df.index.isin(df_train.index)]

In [12]:
df_train.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V9,V10,V11,V12,V14,V16,V17,V18,V19,V21,Amount,Class
244333,152307.0,-5.222968,4.641827,-8.858204,7.723502,-1.507035,-2.159484,-4.205164,-1.505637,-2.239066,4.231393,-8.493488,-13.237559,-4.186415,-5.492536,-1.216108,1.046105,0.561892,1.00,1
95534,65358.0,1.193916,-0.571085,0.742522,-0.014588,-0.624561,0.832162,-0.833350,1.169425,-0.371672,-0.245677,1.375941,-0.819319,0.125853,-0.397246,0.272377,1.226022,-0.049502,31.91,1
40525,40276.0,1.159373,2.844795,-4.050680,4.777701,2.948980,-2.010361,1.744086,-2.450198,-2.042168,1.844093,-2.425933,-7.208312,2.375296,6.443510,2.591846,-2.889770,-0.176541,1.00,1
83053,59669.0,0.326007,1.286638,-2.007181,2.419675,-1.532902,-1.432803,-2.459530,-1.125861,-3.236784,3.561795,-3.914679,-4.458895,-2.343304,-5.071450,-0.749172,0.228423,0.556895,6.27,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,-1.127396,-3.232153,2.858466,-3.096915,-5.210141,-2.155297,-3.267116,-0.688505,0.737657,0.370612,0.76,1

In [13]:
df_test.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V9,V10,V11,V12,V14,V16,V17,V18,V19,V21,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.363787,0.090794,-0.551600,-0.617801,-0.311169,-0.470401,0.207971,0.025791,0.403993,-0.018307,149.62,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,-1.387024,-0.054952,-0.226487,0.178228,-0.287924,-1.059647,-0.684093,1.965775,-1.232622,-0.108300,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,0.817739,0.753074,-0.822843,0.538196,-1.119670,-0.451449,-0.237033,-0.038195,0.803487,-0.009431,69.99,0
10,10.0,1.449044,-1.176339,0.913860,-1.375667,-1.971383,-0.629152,-1.423236,-1.720408,1.626659,1.199644,-0.671440,-0.095045,0.031967,0.253415,0.854344,-0.221365,-0.009302,7.80,0
12,10.0,1.249999,-1.221637,0.383930,-1.234899,-1.485419,-0.753230,-0.689405,-2.094011,1.323729,0.227666,-0.242682,-0.317631,-0.815612,0.873936,-0.847789,-0.683193,-0.231809,121.50,0

In [14]:
def transform_feature_cols(df):
  """
  Transform each feature in features so that it has a mean of 0 and standard deviation of 1; 
  This helps with training the neural network.
  """
  features = df.columns.values
  for feature in features:
    if feature != 'Class':
      mean, std = df[feature].mean(), df[feature].std()
      df.loc[:, feature] = (df[feature] - mean) / std
  return df

In [15]:
df_train.loc[:] = transform_feature_cols(df_train)

In [16]:
df_test.loc[:] = transform_feature_cols(df_test)

/usr/local/envs/py3env/lib/python3.5/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

<b>Preprocessed files with header<b>

In [17]:
df_train.to_csv('./data/preprocess/creditcard_header_train.csv', sep=',', encoding='utf-8', index=False)
df_test.to_csv('./data/preprocess/creditcard_header_test.csv', sep=',', encoding='utf-8', index=False)

<b>Preprocessed files without header - required for google cloud ml and read_dataset with csv file format</b>

In [18]:
df_train.to_csv('./data/preprocess/creditcard_train.csv', sep=',', encoding='utf-8', header=False, index=False)
df_test.to_csv('./data/preprocess/creditcard_test.csv', sep=',', encoding='utf-8', header=False, index=False)

In [19]:
df_train = pd.read_csv('./data/preprocess/creditcard_header_train.csv')
df_train.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V9,V10,V11,V12,V14,V16,V17,V18,V19,V21,Amount,Class
0,1.211324,-2.663296,2.811125,-5.821903,5.448855,-1.084869,-1.616218,-3.373310,-1.370401,-2.052884,4.145017,-8.487580,-13.803510,-4.769368,-6.437397,-1.449438,1.281791,0.772919,-0.351896,1
1,-0.619685,0.608662,-0.344922,0.488542,-0.012305,-0.449342,0.622788,-0.667193,1.065999,-0.340233,-0.239191,1.373967,-0.854617,0.143191,-0.464781,0.324412,1.502524,-0.066230,-0.227603,1
2,-1.147872,0.591048,1.723150,-2.661973,3.369855,2.124198,-1.504612,1.401380,-2.230690,-1.872302,1.807233,-2.424871,-7.516622,2.705769,7.553840,3.088557,-3.546952,-0.240592,-0.351896,1
3,-0.739486,0.166116,0.779797,-1.318806,1.705677,-1.103498,-1.072356,-1.972316,-1.024508,-2.967925,3.489307,-3.912428,-4.649718,-2.669686,-5.943807,-0.892984,0.278615,0.766060,-0.330704,1
4,1.570160,0.702811,0.781458,-3.288742,0.994404,0.319176,-0.992824,-1.132539,-1.025906,-2.963678,2.800566,-3.095317,-5.433066,-2.455507,-3.828796,-0.820686,0.903372,0.510384,-0.352861,1

In [20]:
df_train.Class.unique()

array([1, 0])

In [21]:
df_train['Class'].value_counts()

0    227452
1       394
Name: Class, dtype: int64

In [22]:
df_test = pd.read_csv('./data/preprocess/creditcard_header_test.csv')
df_test.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V9,V10,V11,V12,V14,V16,V17,V18,V19,V21,Amount,Class
0,-1.998801,-0.697323,-0.047440,1.693993,0.984401,-0.253105,0.351256,0.192772,0.326700,0.081273,-0.546980,-0.618760,-0.324035,-0.539943,0.245808,0.031650,0.505425,-0.030746,0.242086,0
1,-1.998780,-0.495381,-0.115603,1.196932,-0.603516,-0.009493,0.947322,0.191115,-1.263025,-0.053326,-0.227876,0.183054,-0.299743,-1.217219,-0.823710,2.356741,-1.515581,-0.149505,0.139964,0
2,-1.998759,-0.593885,0.528751,1.033591,0.293592,-0.304257,0.072925,0.487029,0.738886,0.692898,-0.813211,0.545638,-1.168946,-0.518160,-0.287719,-0.045037,0.998747,-0.019033,-0.069244,0
3,-1.998591,0.744030,-0.716402,0.609078,-0.966501,-1.465972,-0.477767,-1.192005,-1.565736,1.499667,1.171902,-0.672789,-0.098178,0.037475,0.300291,1.024679,-0.266811,-0.018863,-0.312388,0
4,-1.998591,0.641891,-0.743861,0.254728,-0.866776,-1.105049,-0.572004,-0.580885,-1.904965,1.219906,0.217885,-0.240915,-0.330788,-0.936727,1.044250,-1.015343,-0.837108,-0.312491,0.132145,0

In [23]:
df_test.Class.unique()

array([0, 1])

In [24]:
df_test['Class'].value_counts()

0    56863
1       98
Name: Class, dtype: int64

<b>Preprocessing for having one hot encoding for class label <b>

In [25]:
df_train.loc[df_train.Class == 0, 'Normal'] = 1
df_train.loc[df_train.Class == 1, 'Normal'] = 0
df_train_ohe = df_train.rename(columns={'Class': 'Fraud'})
df_train_ohe.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V9,V10,V11,V12,V14,V16,V17,V18,V19,V21,Amount,Fraud,Normal
0,1.211324,-2.663296,2.811125,-5.821903,5.448855,-1.084869,-1.616218,-3.373310,-1.370401,-2.052884,4.145017,-8.487580,-13.803510,-4.769368,-6.437397,-1.449438,1.281791,0.772919,-0.351896,1,0.0
1,-0.619685,0.608662,-0.344922,0.488542,-0.012305,-0.449342,0.622788,-0.667193,1.065999,-0.340233,-0.239191,1.373967,-0.854617,0.143191,-0.464781,0.324412,1.502524,-0.066230,-0.227603,1,0.0
2,-1.147872,0.591048,1.723150,-2.661973,3.369855,2.124198,-1.504612,1.401380,-2.230690,-1.872302,1.807233,-2.424871,-7.516622,2.705769,7.553840,3.088557,-3.546952,-0.240592,-0.351896,1,0.0
3,-0.739486,0.166116,0.779797,-1.318806,1.705677,-1.103498,-1.072356,-1.972316,-1.024508,-2.967925,3.489307,-3.912428,-4.649718,-2.669686,-5.943807,-0.892984,0.278615,0.766060,-0.330704,1,0.0
4,1.570160,0.702811,0.781458,-3.288742,0.994404,0.319176,-0.992824,-1.132539,-1.025906,-2.963678,2.800566,-3.095317,-5.433066,-2.455507,-3.828796,-0.820686,0.903372,0.510384,-0.352861,1,0.0

In [26]:
df_test.loc[df_test.Class == 0, 'Normal'] = 1
df_test.loc[df_test.Class == 1, 'Normal'] = 0
df_test_ohe = df_test.rename(columns={'Class': 'Fraud'})
df_test_ohe.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V9,V10,V11,V12,V14,V16,V17,V18,V19,V21,Amount,Fraud,Normal
0,-1.998801,-0.697323,-0.047440,1.693993,0.984401,-0.253105,0.351256,0.192772,0.326700,0.081273,-0.546980,-0.618760,-0.324035,-0.539943,0.245808,0.031650,0.505425,-0.030746,0.242086,0,1.0
1,-1.998780,-0.495381,-0.115603,1.196932,-0.603516,-0.009493,0.947322,0.191115,-1.263025,-0.053326,-0.227876,0.183054,-0.299743,-1.217219,-0.823710,2.356741,-1.515581,-0.149505,0.139964,0,1.0
2,-1.998759,-0.593885,0.528751,1.033591,0.293592,-0.304257,0.072925,0.487029,0.738886,0.692898,-0.813211,0.545638,-1.168946,-0.518160,-0.287719,-0.045037,0.998747,-0.019033,-0.069244,0,1.0
3,-1.998591,0.744030,-0.716402,0.609078,-0.966501,-1.465972,-0.477767,-1.192005,-1.565736,1.499667,1.171902,-0.672789,-0.098178,0.037475,0.300291,1.024679,-0.266811,-0.018863,-0.312388,0,1.0
4,-1.998591,0.641891,-0.743861,0.254728,-0.866776,-1.105049,-0.572004,-0.580885,-1.904965,1.219906,0.217885,-0.240915,-0.330788,-0.936727,1.044250,-1.015343,-0.837108,-0.312491,0.132145,0,1.0

In [32]:
df_train_ohe=df_train_ohe.astype({"Normal": int, "Fraud": int})
df_train_ohe.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V9,V10,V11,V12,V14,V16,V17,V18,V19,V21,Amount,Fraud,Normal
0,1.211324,-2.663296,2.811125,-5.821903,5.448855,-1.084869,-1.616218,-3.373310,-1.370401,-2.052884,4.145017,-8.487580,-13.803510,-4.769368,-6.437397,-1.449438,1.281791,0.772919,-0.351896,1,0
1,-0.619685,0.608662,-0.344922,0.488542,-0.012305,-0.449342,0.622788,-0.667193,1.065999,-0.340233,-0.239191,1.373967,-0.854617,0.143191,-0.464781,0.324412,1.502524,-0.066230,-0.227603,1,0
2,-1.147872,0.591048,1.723150,-2.661973,3.369855,2.124198,-1.504612,1.401380,-2.230690,-1.872302,1.807233,-2.424871,-7.516622,2.705769,7.553840,3.088557,-3.546952,-0.240592,-0.351896,1,0
3,-0.739486,0.166116,0.779797,-1.318806,1.705677,-1.103498,-1.072356,-1.972316,-1.024508,-2.967925,3.489307,-3.912428,-4.649718,-2.669686,-5.943807,-0.892984,0.278615,0.766060,-0.330704,1,0
4,1.570160,0.702811,0.781458,-3.288742,0.994404,0.319176,-0.992824,-1.132539,-1.025906,-2.963678,2.800566,-3.095317,-5.433066,-2.455507,-3.828796,-0.820686,0.903372,0.510384,-0.352861,1,0

In [33]:
df_train_ohe.Fraud.unique()

array([1, 0])

In [34]:
df_train_ohe['Fraud'].value_counts()

0    227452
1       394
Name: Fraud, dtype: int64

In [35]:
df_train_ohe.Normal.unique()

array([0, 1])

In [36]:
df_train_ohe['Normal'].value_counts()

1    227452
0       394
Name: Normal, dtype: int64

In [37]:
df_test_ohe=df_test_ohe.astype({"Normal": int, "Fraud": int})
df_test_ohe.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V9,V10,V11,V12,V14,V16,V17,V18,V19,V21,Amount,Fraud,Normal
0,-1.998801,-0.697323,-0.047440,1.693993,0.984401,-0.253105,0.351256,0.192772,0.326700,0.081273,-0.546980,-0.618760,-0.324035,-0.539943,0.245808,0.031650,0.505425,-0.030746,0.242086,0,1
1,-1.998780,-0.495381,-0.115603,1.196932,-0.603516,-0.009493,0.947322,0.191115,-1.263025,-0.053326,-0.227876,0.183054,-0.299743,-1.217219,-0.823710,2.356741,-1.515581,-0.149505,0.139964,0,1
2,-1.998759,-0.593885,0.528751,1.033591,0.293592,-0.304257,0.072925,0.487029,0.738886,0.692898,-0.813211,0.545638,-1.168946,-0.518160,-0.287719,-0.045037,0.998747,-0.019033,-0.069244,0,1
3,-1.998591,0.744030,-0.716402,0.609078,-0.966501,-1.465972,-0.477767,-1.192005,-1.565736,1.499667,1.171902,-0.672789,-0.098178,0.037475,0.300291,1.024679,-0.266811,-0.018863,-0.312388,0,1
4,-1.998591,0.641891,-0.743861,0.254728,-0.866776,-1.105049,-0.572004,-0.580885,-1.904965,1.219906,0.217885,-0.240915,-0.330788,-0.936727,1.044250,-1.015343,-0.837108,-0.312491,0.132145,0,1

In [40]:
df_test_ohe.Fraud.unique()

array([0, 1])

In [44]:
df_test_ohe['Fraud'].value_counts()

0    56863
1       98
Name: Fraud, dtype: int64

In [45]:
df_test_ohe.Normal.unique()

array([1, 0])

In [46]:
df_test_ohe['Normal'].value_counts()

1    56863
0       98
Name: Normal, dtype: int64

<b>Write to CSV files<b>

In [47]:
df_train_ohe.to_csv('./data/preprocess/creditcard_ohe_header_train.csv', sep=',', encoding='utf-8', index=False)
df_test_ohe.to_csv('./data/preprocess/creditcard_ohe_header_test.csv', sep=',', encoding='utf-8', index=False)

In [48]:
df_train_ohe.to_csv('./data/preprocess/creditcard_ohe_train.csv', sep=',', encoding='utf-8', header=False, index=False)
df_test_ohe.to_csv('./data/preprocess/creditcard_ohe_test.csv', sep=',', encoding='utf-8', header=False, index=False)

<pre>
# Copyright 2018 Atos. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
</pre>